### ISSUE TITLE
Strange build error

### ISSUE THREAD

**Issue by kevinrenskers** [SwiftPackageIndex/SwiftPackageIndex-Server#1665] opened 2022-04-01 17:28 UTC
I'm getting a strange build failure in my package [Saga](https://swiftpackageindex.com/loopwerk/Saga/builds), but only for the "Swift 5.5 for macOS (Xcode) using Xcode 13.2.1" build:

![Screen Shot 2022-04-01 at 18 58 03](https://user-images.githubusercontent.com/229384/161312723-857ab6b8-feb1-4fdf-ab31-7b5c0aeb0ffb.png)

The weird thing is that 1.1.3 and main are the same code, and main succeeds just fine.

This is the build that's failing: https://swiftpackageindex.com/builds/6B1A7920-B91E-41DE-84BA-675914C4BBB6

![Screen Shot 2022-04-01 at 18 53 01](https://user-images.githubusercontent.com/229384/161312785-4a8bae74-a1f5-43a6-8f1c-e15eb6780df5.png)

**Comment by daveverwer** [comment] 2022-04-01 19:11
Thanks Kevin! 

I've not had a chance to look at this in detail yet but there are a few commits between the tagged version and `main`. They look to be inconsequential but let's check it. Could you run the exact build command from the top of the failed build with the same commit checked out please? 

That said, the "unable to restore state" message does look suspicious, but step one would be to make sure it doesn't also fail for you.

We'll take a closer look after the weekend. 

Thanks!

**Comment by kevinrenskers** [comment] 2022-04-01 19:17
Those commits are completely unrelated to the code itself, and since it fails for "Xcode" yet succeeds for "Xcode, ARM", I am not sure I could even reproduce the build, as I am on an M1 Mac. Still, happy to try it out, but I don't know what build command to use? I can't find anything to copy from the failed build.

But yeah no rush! Have a great weekend.

**Comment by daveverwer** [comment] 2022-04-01 19:21
The build command is in a separate box, just above the build log. I'm on my phone right now or I'd take a screenshot, but it's just above the logs and has the label "Build Command". 

The build will run fine in a M1 machine. In fact, all our builders are now M1-based, so that's all good. 

I saw the commits, but you know computers! 😬 You can't expect consistent output without consistent input!

**Comment by kevinrenskers** [comment] 2022-04-01 19:22
That box just says "error: failed to read build command file"

**Comment by daveverwer** [comment] 2022-04-01 19:25
For archiving purposes, just in case we need to look at this log once this is fixed, here is the full content of the failed log:

```
Clone URL: https://github.com/loopwerk/Saga.git
Reference: 1.1.3
Initialized empty Git repository in /Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace/.git/
From https://github.com/loopwerk/Saga
 * tag               1.1.3      -> FETCH_HEAD
HEAD is now at 0994e9e chore: Remove the swift-docc-plugin dependency (which wasn't directly used by Saga) to make builds pass on Swift Package Index again
Cloned https://github.com/loopwerk/Saga.git into spi-builder-workspace
0994e9e6e1662331248a9fb789d01f8fc2ff9127
Error: Could not find any schemes
Selected platform:         macosXcodebuild
Swift version:             v5_5
Building package at path:  spi-builder-workspace
objc[40709]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1e585e098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb02c8). One of the two will be used. Which one is undefined.
objc[40709]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1e585e0e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb0318). One of the two will be used. Which one is undefined.
objc[40709]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1e585deb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb04f8). One of the two will be used. Which one is undefined.
objc[40709]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e585df00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb0548). One of the two will be used. Which one is undefined.
objc[40709]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e585df50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb0598). One of the two will be used. Which one is undefined.
objc[40709]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1e585dfa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb05e8). One of the two will be used. Which one is undefined.
objc[40709]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1e585dff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb0638). One of the two will be used. Which one is undefined.
objc[40709]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1e585e040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb0688). One of the two will be used. Which one is undefined.
Command line invocation:
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=/Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies -resolvePackageDependencies

User defaults from command line:
    IDEClonedSourcePackagesDirPathOverride = /Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies
    IDEPackageSupportUseBuiltinSCM = YES

unable to restore state from /Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies/workspace-state.json; unsupported schema version 5
Resolve Package Graph

Fetching from https://github.com/JohnSundell/Codextended.git (cached)

Fetching from https://github.com/kylef/PathKit (cached)

Fetching from https://github.com/kylef/Spectre.git (cached)

Cloning local copy of package ‘Spectre’

Checking out 0.10.1 of package ‘Spectre’

Cloning local copy of package ‘Codextended’

Checking out 0.3.0 of package ‘Codextended’

Cloning local copy of package ‘PathKit’

Checking out 1.0.1 of package ‘PathKit’


Resolved source packages:
  Spectre: https://github.com/kylef/Spectre.git @ 0.10.1
  PathKit: https://github.com/kylef/PathKit @ 1.0.1
  Saga: /Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace
  Codextended: https://github.com/JohnSundell/Codextended.git @ 0.3.0

resolved source packages: Spectre, PathKit, Saga, Codextended
warning: unable to restore checkouts state: unable to restore state from /Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies/repositories/checkouts-state.json; missingKey("status")
objc[41275]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1e585e098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c02c8). One of the two will be used. Which one is undefined.
objc[41275]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1e585e0e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c0318). One of the two will be used. Which one is undefined.
objc[41275]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1e585deb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c04f8). One of the two will be used. Which one is undefined.
objc[41275]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e585df00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c0548). One of the two will be used. Which one is undefined.
objc[41275]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e585df50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c0598). One of the two will be used. Which one is undefined.
objc[41275]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1e585dfa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c05e8). One of the two will be used. Which one is undefined.
objc[41275]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1e585dff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c0638). One of the two will be used. Which one is undefined.
objc[41275]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1e585e040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1065c0688). One of the two will be used. Which one is undefined.
{
  "workspace" : {
    "name" : "spi-builder-workspace",
    "schemes" : [
      "Saga",
      "Saga-Package",
      "watch"
    ]
  }
}
warning: unable to restore checkouts state: unable to restore state from /Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies/repositories/checkouts-state.json; missingKey("status")
objc[41312]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1e585e098) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1045102c8). One of the two will be used. Which one is undefined.
objc[41312]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1e585e0e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104510318). One of the two will be used. Which one is undefined.
objc[41312]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1e585deb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1045104f8). One of the two will be used. Which one is undefined.
objc[41312]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e585df00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104510548). One of the two will be used. Which one is undefined.
objc[41312]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e585df50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104510598). One of the two will be used. Which one is undefined.
objc[41312]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1e585dfa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1045105e8). One of the two will be used. Which one is undefined.
objc[41312]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1e585dff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104510638). One of the two will be used. Which one is undefined.
objc[41312]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1e585e040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104510688). One of the two will be used. Which one is undefined.
{
  "workspace" : {
    "name" : "spi-builder-workspace",
    "schemes" : [
      "Saga",
      "Saga-Package",
      "watch"
    ]
  }
}
warning: unable to restore checkouts state: unable to restore state from /Users/builder/builds/1hFCVExo/0/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies/repositories/checkouts-state.json; missingKey("status")
FAILURE 5.5 macos-xcodebuild
```

**Comment by daveverwer** [comment] 2022-04-01 19:35
I've re-queued that build. It should start a new build for that configuration shortly.

**Comment by daveverwer** [comment] 2022-04-01 19:36
It failed again. We'll need to look into this next week.

**Comment by kevinrenskers** [comment] 2022-04-01 19:40
I found the build command by looking at the `main` build, and just ran that on the specific 1.1.3 commit. Succeeds just fine locally, for what it's worth.

`env DEVELOPER_DIR="/Applications/Xcode.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" build -scheme "Saga-Package" -destination 'platform=macos,arch=x86_64'`

**Comment by kevinrenskers** [comment] 2022-04-01 19:40
> It failed again. We'll need to look into this next week.

Like I said, no rush! Thanks for the effort so far already.

**Comment by daveverwer** [comment] 2022-04-04 13:21
Hi Kevin

I spent some time trying to reproduce this failure today and can't reproduce it. It definitely happened on the build machine, but unfortunately, that build is now gone as the main branch now moved forward and it was re-built with the latest commit. That build succeeded, and everything looks normal now.

I think we should close this, please do feel free to re-open it if you notice the same issue come back for future commits.

**Closed by daveverwer** 2022-04-04 13:21 UTC
Labels: bug
