### ISSUE TITLE
Ingestion errors (duplicate key et al)

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#540] opened 2020-07-19 09:58 UTC
We're accumulating a number of errors in our ingestion logs. There are two categories:

1. Github API requests that fail with ‘forbidden’ (rate limiting? Last I checked we were far from the limit and I don’t think anything has changed with our processing)
1. duplicate key value violates unique constraint “idx_repositories_owner_name"

#2 is fairly recent (started last Sunday, July 12). Unfortunately we can’t tell from the logs which package triggered the violation.

The best way to debug this is probably by pulling a prod dump, running it locally with a breakpoint on the db error.

[ingestion.log](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/files/4943522/ingestion.log)

**Comment by finestructure** [comment] 2020-07-19 10:01
This has some urgency because a) we don’t want to burn our rollbar quota again due to these errors (reset on July 28) and b) we may be churning on records we can’t actually save.

**Comment by finestructure** [comment] 2020-07-19 10:05
I see two records marked as `ingestion_failed` which might be candidates:

- https://github.com/kean/Future.git
- https://github.com/pvzig/SlackKit.git

`kean/Future` shows a different url on our package page, https://github.com/kean/FutureX.git (https://swiftpackageindex.com/kean/Future)

Equally, there’s an inconsistency for SlackKit. The github url is https://swiftpackageindex.com/pvzig/SlackKit but we show  https://github.com/SlackKit/SlackKit.git on our package page (https://swiftpackageindex.com/pvzig/SlackKit)

**Comment by finestructure** [comment] 2020-07-19 10:15
Ok, I think this might be it. We have an existing https://github.com/kean/FutureX.git in the db and that blocks https://github.com/kean/Future.git from being saved. Same for SlackKit.

I believe the canonical versions are

- https://github.com/kean/Future
- https://github.com/pvzig/SlackKit

and we should remove

- https://github.com/kean/FutureX.git
- https://github.com/SlackKit/SlackKit.git

which are redirects. I’ll open a PR in packages and then I’ll keep this issue open to monitor if this helps with the unique key violations.

Looking through the logs, I see two unique key failures per “pass”:

```
2020-07-16T18:06:12.821648143Z [ ERROR ] duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
2020-07-16T18:06:13.086061273Z [ ERROR ] ingestion error: server: duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
2020-07-16T18:11:16.533236178Z [ ERROR ] duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
2020-07-16T18:11:16.713536609Z [ ERROR ] ingestion error: server: duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
2020-07-16T18:16:20.327264160Z [ ERROR ] duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
2020-07-16T18:16:20.640768050Z [ ERROR ] ingestion error: server: duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
2020-07-16T18:21:24.296594465Z [ ERROR ] duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
2020-07-16T18:21:24.536269010Z [ ERROR ] ingestion error: server: duplicate key value violates unique constraint "idx_repositories_owner_name" (_bt_check_unique)
```

2 errors every 5 minutes is 576 errors per day and that would line up with the error rates we are seeing on Rollbar.

**Comment by finestructure** [comment] 2020-07-19 10:29
There may be something to think through here regarding updates to canonical urls. If I’m not mistaken, we have no real safe guard against importing those duplicates. Consider:

- we have package `foo/a`
- it gets renamed to `foo/b` and we correctly reflect that change in `repositories` as `foo`, `b`
- however, packages url remains as `foo/a`
- the package validation step will check for `foo/b` and not find a match
- so we end up also importing `foo/b` unless the submitter knows they are the same
- this will lead to `foo/b` never being ingested because it can’t save to repositories

One easy check we can do to identify candidates is compare `packages.url` to `repositories.owner` + `repositories.name`. Any packages where these are different are packages that could be imported again.

We can’t simply update `packages.url` though, because that would _automatically_ lead to duplication because on the next reconcliation pass the original would come back as a new package.

So I think as long as we have the package list we need to run passes finding discrepancies and feeding them back into the package list.

**Comment by daveverwer** [comment] 2020-07-19 10:30
> Ok, I think this might be it. We have an existing https://github.com/kean/FutureX.git in the db and that blocks https://github.com/kean/Future.git from being saved. Same for SlackKit.
> 
> I believe the canonical versions are
> 
> * https://github.com/kean/Future
> * https://github.com/pvzig/SlackKit
> 
> and we should remove
> 
> * https://github.com/kean/FutureX.git
> * https://github.com/SlackKit/SlackKit.git
> 
> which are redirects. I’ll open a PR in packages and then I’ll keep this issue open to monitor if this helps with the unique key violations.

Both of those were added in [PackageList#473](https://github.com/SwiftPackageIndex/PackageList/pull/473) which also makes perfect sense. Well sleuthed!

**Comment by daveverwer** [comment] 2020-07-19 10:33
> One easy check we can do to identify candidates is compare `packages.url` to `repositories.owner` + `repositories.name`. Any packages where these are different are packages that could be imported again.
> 
> We can’t simply update `packages.url` though, because that would _automatically_ lead to duplication because on the next reconciliation pass the original would come back as a new package.
> 
> So I think as long as we have the package list we need to run passes finding discrepancies and feeding them back into the package list.

It wouldn't be an ideal solution, as packages can be renamed/moved after ingestion, but at some point it would be good to add something to validation to check for redirects at least as packages are being added.

**Comment by Sherlouk** [comment] 2020-07-19 10:38
Are the problems that were caused by https://github.com/SwiftPackageIndex/PackageList/pull/473 at least not now partially resolved by the redirect following we introduced later in https://github.com/SwiftPackageIndex/PackageList/pull/480?

This of course doesn't help what so ever if a package is renamed/moved after it's added to the package list though.

**Comment by finestructure** [comment] 2020-07-19 10:41
I think the only way to avoid those duplicates was if the validation check both the new package(s) _and_ the existing package list for redirects. Because the problem is very likely going to be a redirect on the index side, which is invisible to the package list without actually going through.

**Comment by finestructure** [comment] 2020-07-19 10:45
Actually, it’s simple to test by just trying to add `kean/FutureX` back:

```
❯ swift validate.swift 
- https://github.com/rnine/Checksum.git
- https://github.com/marmelroy/Zip.git
+ https://github.com/kean/FutureX.git

*******************************************************************************
** IMPORTANT ******************************************************************

During validation, problem(s) were found:

* The packages.json file contained duplicate rows
* Found "https://github.com/kean/FutureX.git" but this redirected to "https://github.com/kean/Future"

These problems have been automatically fixed, but you'll need to commit the
changes that this script has made before creating the pull request.

Thanks!

*******************************************************************************

Passed validation but please commit the changes made by the script before creating the pull request.
```

While it was the other way around originally it still shows that unless you check both sides for redirects you can’t know if it’ll cause collisions.

**Comment by finestructure** [comment] 2020-07-19 10:48
Actually, that’s the solution, isn’t it? We run a nightly job on the full package list that updates any redirected packages?

**Comment by Sherlouk** [comment] 2020-07-19 10:48
Well the validator script currently "assumed" that everything else in the list is gospel and doesn't contain redirects, that is, of course, not actually true.

The second something is outdated (by a repo being moved/renamed after it's added to the index) we get into problems where, as you highlight, we don't know if there's a collision because we only check the diff'd libraries.

**Comment by Sherlouk** [comment] 2020-07-19 10:50
I think it's definitely worth investigating doing some sort of regular automated audit of the full package list.

I also wonder if we should be looking to improve the reporting on this problem. Getting a bunch of duplicate key violations isn't super helpful on it's own -- if we can improve that error flow to tell us exactly which two libraries are colliding then we can more easily create targeted scripts to fix the problem much quicker.

**Comment by daveverwer** [comment] 2020-07-23 10:05
I think we can close this now.

**Closed by daveverwer** 2020-07-23 10:05 UTC
