### ISSUE TITLE
Documentation for swift-openapi-runtime is missing

### ISSUE THREAD

**Issue by czechboy0** [SwiftPackageIndex/SwiftPackageIndex-Server#3464] opened 2024-10-29 14:05 UTC
**Please describe the bug**

The documentation for swift-openapi-runtime is missing: https://swiftpackageindex.com/apple/swift-openapi-runtime/documentation

**Explain the steps needed to reproduce the bug**

1. Navigate to https://swiftpackageindex.com/apple/swift-openapi-runtime/documentation
2. See the error 404 - Not Found

**What was the expected behaviour?**

Rendered documentation, it worked correctly for over a year.

**Screenshots**

If applicable, please add screenshots to help explain your problem.

**What web browser were you using? (if relevant)**

Safari

If you're reporting a bug with the front end, please include your browser information below:

- Platform: Desktop/Tablet/Smartphone
- Browser [e.g. Chrome, Safari]
- Version [e.g. Version 15.1]

**Additional context**

Is there anything else we might find useful?

**Comment by daveverwer** [comment] 2024-10-29 14:07
Are you still seeing this now? It shows the documentation for me.

**Comment by czechboy0** [comment] 2024-10-29 14:22
Fascinating, I cleaned caches and tried from a private window, and still get 404 for this URL: https://swiftpackageindex.com/apple/swift-openapi-runtime/1.5.0/documentation/openapiruntime

**Comment by daveverwer** [comment] 2024-10-29 14:23
How about if you do it via `curl`?

![Screenshot 2024-10-29 at 14 23 35@2x](https://github.com/user-attachments/assets/8f6ade49-234a-44d7-aea5-ec9714044a93)

**Comment by czechboy0** [comment] 2024-10-29 14:26
I still get 404:

```
curl https://swiftpackageindex.com/apple/swift-openapi-runtime/1.5.0/documentation/openapiruntime
<!DOCTYPE html><html lang="en"><!--Version: 2.111.5--><!--DB Id: prod-3--><head><meta name="viewport" content="width=device-width, initial-scale=1.0"/><meta charset="UTF-8"/><meta property="og:site_name" content="The Swift Package Index"/><link rel="canonical" href="https://swiftpackageindex.com/apple/swift-openapi-runtime/1.5.0/documentation/openapiruntime"/><meta name="twitter:url" content="https://swiftpackageindex.com/apple/swift-openapi-runtime/1.5.0/documentation/openapiruntime"/><meta property="og:url" content="https://swiftpackageindex.com/apple/swift-openapi-runtime/1.5.0/documentation/openapiruntime"/><title>404 - Not Found &ndash; Error &ndash; Swift Package Index</title><meta name="twitter:title" content="404 - Not Found &ndash; Error &ndash; Swift Package Index"/><meta property="og:title" content="404 - Not Found &ndash; Error &ndash; Swift Package Index"/><meta name="description" content="The Swift Package Index is the place to find the best Swift packages."/><meta name="twitter:description" content="The Swift Package Index is the place to find the best Swift packages."/><meta property="og:description" content="The Swift Package Index is the place to find the best Swift packages."/><meta name="twitter:card" content="summary"/><meta name="twitter:image" content="https://swiftpackageindex.com/images/logo.png"/><meta property="og:image" content="https://swiftpackageindex.com/images/logo.png"/><link rel="shortcut icon" href="/images/logo-tiny.png" type="image/png"/><link rel="alternate" type="application/rss+xml" title="Swift Package Index Blog" href="https://swiftpackageindex.com/blog/feed.xml"/><link rel="alternate" type="application/rss+xml" title="Swift Package Index – Recently Added Packages" href="https://swiftpackageindex.com/packages.rss"/><link rel="alternate" type="application/rss+xml" title="Swift Package Index – Recent Package Releases" href="https://swiftpackageindex.com/releases.rss"/><link rel="alternate" type="application/rss+xml" title="Swift Package Index – Recent Major Package Releases" href="https://swiftpackageindex.com/releases.rss?major=true"/><link rel="alternate" type="application/rss+xml" title="Swift Package Index – Recent Major & Minor Package Releases" href="https://swiftpackageindex.com/releases.rss?major=true&minor=true"/><link rel="alternate" type="application/rss+xml" title="Swift Package Index – Recent Package Pre-Releases" href="https://swiftpackageindex.com/releases.rss?pre=true"/><link rel="stylesheet" href="/shared.css?2.111.5" data-turbolinks-track="reload"/><link rel="stylesheet" href="/main.css?2.111.5" data-turbolinks-track="reload"/><script src="/shared.js?2.111.5" data-turbolinks-track="reload" defer></script><script src="/main.js?2.111.5" data-turbolinks-track="reload" defer></script><script async defer data-domain="swiftpackageindex.com" src="https://plausible.io/js/plausible.outbound-links.js"></script>
<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script></head><body><header><div class="inner"><a href="/"><h1><img alt="The Swift Package Index logo." src="/images/logo.svg"/>Swift Package Index</h1></a><nav><ul><li><a class="supporters" href="/supporters">Supporters</a></li><li><a href="/add-a-package">Add a Package</a></li><li><a href="/blog">Blog</a></li><li><a href="/faq">FAQ</a></li><li class="search"><form action="/search"><input id="query" name="query" type="search" placeholder="Search" spellcheck="false" autocomplete="off" data-gramm="false" data-focus="false"/><button type="submit"><div title="Search"></div></button></form></li></ul></nav></div></header><p class="announcement">Track the adoption of Swift 6 strict concurrency checks for data race safety. How many packages are <a href="/ready-for-swift-6">Ready for Swift 6</a>?</p><main><div class="inner"><section class="error-message"><h4>404 - Not Found</h4><p>If you were expecting to find a page here, please <a href="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/new/choose">raise an issue</a>.</p><p>From here, you'll want to <a href="/">go to the home page</a> or <a href="/search">search for a package</a>.</p></section></div></main><footer><div class="inner"><nav><ul><li><a href="/blog">Blog</a></li><li><a href="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server">GitHub</a></li><li><a href="/privacy">Privacy and Cookies</a></li><li><a href="https://swiftpackageindex.statuspage.io">Uptime and System Status</a></li><li><a href="/build-monitor">Build System Monitor</a></li><li><a href="https://mas.to/@SwiftPackageIndex">Mastodon</a></li></ul><small>The Swift Package Index is entirely funded by community sponsorship. Thank you to <a href="https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server#funding-and-sponsorship">all our sponsors for their generosity</a>.</small><small>The Swift Package Index is operated by SPI Operations Limited, a company registered in the UK with company number 13466692.</small><a rel="me" href="https://mas.to/@SwiftPackageIndex"></a><a rel="me" href="https://mas.to/@SwiftPackageUpdates"></a></nav></div></footer><spi-debug-panel class="hidden"><table><tbody></tbody></table></spi-debug-pane
<img width="1120" alt="Screenshot 2024-10-29 at 3 25 30 PM" src="https://github.com/user-attachments/assets/f465141c-adc3-4919-be5c-dcb95d6f03b7">
l></body></html>
```

**Comment by daveverwer** [comment] 2024-10-29 14:27
Could you run it with the `-I` and make sure you get a 200 from that, please?

**Comment by czechboy0** [comment] 2024-10-29 14:28
Yup, sorry:

```
curl -I https://swiftpackageindex.com/apple/swift-openapi-runtime/1.5.0/documentation/openapiruntime
HTTP/2 404 
date: Tue, 29 Oct 2024 14:28:10 GMT
content-type: text/html; charset=utf-8
content-length: 5266
cache-control: max-age=10800
cf-cache-status: HIT
age: 1520
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=XOCdFf77KOtuPJJBeB9%2BBdqDsNHeWS%2FQImzNNNCtxpx%2BN%2Buu%2FCsoApD4WV36Z%2BO9vqpDr%2BNb5NHsobwkKstOPiRfsJTkl2x2CG4n17N3fatanHb54VcnbI2k4d6u84AlH%2B%2Bt%2Fo8g6Ja8Kn72p5QsTjiKEw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 8da3d9bb194306c4-AMS
```

**Comment by daveverwer** [comment] 2024-10-29 14:54
So this appears to be a CloudFlare cache issue, but only with some CloudFlare caching servers.

From here in the UK it's a 200. From France it's also a 200. But, if I VPN to the Netherlands, it's a 404. Somehow, the CloudFlare cache in NL has got a bad version of that page.

I can not explain how this happened other than to say something must have happened at around 14:02 UTC today which is the age of the version you got in your response to cause that URL to 404. I can't explain that at the moment.

**Comment by daveverwer** [comment] 2024-10-29 16:09
First of all let me apologise for this incident. I have now done as thorough investigation as I can into what happened and why.

At 14:02:50 the Swift Package Index  served a 404 error for the 1.5.0 documentation:

![Screenshot 2024-10-29 at 15 44 52@2x](https://github.com/user-attachments/assets/54f1ca43-7ce9-47aa-8990-2dbfc5596c25)

Why we served a 404 at that point remains a mystery (more on this at the end) but it was an isolated incident. We served one other 404 7 seconds before this and another 1 second after it, but those were valid 404s. **This was an isolated event and was not part of a large scale failure.**

This timestamp matches up perfectly with what you saw in your request. From your log above:

```
date: Tue, 29 Oct 2024 14:28:10 GMT
age: 1520
```

Your access date 14:28:10 - 1520 seconds (from the “age” header) is exactly 14:02:50. So this matches up perfectly.

SPI served Cloudflare a HTTP 404 at that time and it cached it, but only on its Netherlands-based cache server. All other cache servers that I tried correctly cached and rendered with HTTP 200, as expected. However, when I VPNed to the Netherlands I could also reproduce the HTTP 404.

First things first. I have now reset our Cloudflare cache and the issue went away. This happened about an hour ago, I have been investigating further and writing this up since then.

Please let me know if you see any 404 errors at the moment, but I am fairly certain you won’t!

—

Next, why did we serve a 404?

I don’t have a great answer for this. The last time we [generated the documentation for 1.5.0](https://swiftpackageindex.com/builds/ADCA9BFF-1CEE-4CD1-AB22-458FC77D9B27) was on the 14th October so it was not a problem with propagation of documentation up to S3 or anything like that.

I do not have a good answer for why we served the 404, but I’m going to think about what monitoring we can do to detect issues like this in case it’s an intermittent but persistent issue.

**Comment by czechboy0** [comment] 2024-10-29 17:30
Please close it Dave when you see fit - my issue is gone, but I don't want to close this in case you'd like to use it to track further steps.

**Comment by daveverwer** [comment] 2024-10-29 17:37
> You know, this would be a great lightning talk at some future Swift on Server Conference 👀 How you debugged it, what you found, etc.

I'll title it "Hundreds of thousands of 200s and one 404" 😂

Thanks @czechboy0. I'll close this now

**Closed by daveverwer** 2024-10-29 17:37 UTC
Labels: bug
