### ISSUE TITLE
Linux build failure log doesn't include enough information

### ISSUE THREAD

**Issue by mattmassicotte** [SwiftPackageIndex/SwiftPackageIndex-Server#1982] opened 2022-08-19 15:08 UTC
I have a package that is failing to build on Linux. I thought it *should* work, so I wanted to have a look. But, the build log doesn't seem to include enough information about what went wrong.

Package: https://swiftpackageindex.com/ChimeHQ/ConcurrencyPlus
Example failure: https://swiftpackageindex.com/builds/5FA3E3A3-342E-4534-9925-BC3EA18F00AB

**Comment by finestructure** [comment] 2022-08-22 14:15
I've had a look and it's definitely the `-t` flag on the docker commands (neither in `build.sh` nor in the nested processes) that I initially suspected.

It must have something to do with the way `Process.stdout/stderr.fileHandleForReading` is working on Linux. I know this used to work in the past but there've been a few changes in the meantime. I know this broke a while back, too, so it's not a recent regressions.

Still looking.

**Comment by finestructure** [comment] 2022-08-23 06:46
I'm at a loss here. I've tried

- `-t` in the docker commands
- with and without `fflush` and `setbuf(stdout, nil)`
- non-streaming logging (which `ShellOut` doesn't seem to support on Linux anyway)

but the best I can get is inconsistent, partial logs. This is for two different Swift versions for our SemanticVersion package:

<img width="833" alt="CleanShot 2022-08-23 at 08 39 13@2x" src="https://user-images.githubusercontent.com/65520/186089179-02a989a8-ae7a-420d-8389-24d252742b8c.png">

<img width="808" alt="CleanShot 2022-08-23 at 08 39 29@2x" src="https://user-images.githubusercontent.com/65520/186089200-f705e9e5-4ded-4db8-beb5-ca0eec00d840.png">

For comparison, here's what the `macoc-spm` build logs:

<img width="667" alt="CleanShot 2022-08-23 at 08 43 24@2x" src="https://user-images.githubusercontent.com/65520/186089364-674d276b-ecb6-4935-b6de-02a4ff3e7fdc.png">

**Comment by finestructure** [comment] 2022-08-23 06:49
I'll have to time box this now but there's at least one improvement we'll get out of this: the build command should now be displayed when a build fails. This should make it much easier to replicate the build locally, which is particularly reproducible in case of builds run via docker.

**Comment by finestructure** [comment] 2022-08-23 06:55
I just noticed something rather baffling: the `macos-spm` is _also_ missing something in the logs - but something different, something which is present in the Linux logs: the build command. Here's the current code around this section:

```swift
    Logger.log("Running build ...")
    Logger.log(cmd.string)

    if platform == .linux {
        // Log streaming is not supported in ShellOut on Linux, we need to log everything at once.
        print("========== Linux ==========")
        Logger.log(
            try Current.shell.run(command: cmd, at: path)
        )
#if os(Linux)
        fflush(stdout)
        fflush(stderr)
#endif
        print("===========================")
    } else {
        try Current.shell.run(command: cmd, at: path, xcbeautify: platform.xcbeautify)
    }
```

I don't see the output of `Logger.log(cmd.string)`. The string `warning: Usage of /Users/builder/Library/org.swift.swiftpm/collections.json has been deprecated.` appears where I'd expect to see it.

(This warning should have nothing to do with things, I believe it's the first line of the `run(...)` output.)

**Comment by finestructure** [comment] 2022-08-23 06:59
I think I have a clue. Where you run `swift build` interactively, it logs progress on the same line. I suspect this is what's happening: there's a difference in how this logs on macOS and Linux and one treats it like an interactive terminal and the other doesn't.

I'll try once again without the `-t` to see if I missed a variant.

**Comment by finestructure** [comment] 2022-08-23 08:37
That was it:

<img width="780" alt="CleanShot 2022-08-23 at 10 35 26@2x" src="https://user-images.githubusercontent.com/65520/186112337-d9f26bac-5d78-4275-9535-4b59412a735d.png">

Turns out, as usual, the best bugs are two combined. First, logging didn't work, because streaming logs doesn't work on Linux. So my test with and without `-t` had no effect.

When I switched to non-streaming I left the `-t` in and _that_ then prevented it from working correctly.

I'll keep this open until the builder is deployed.

**Comment by finestructure** [comment] 2022-08-23 09:30
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/142

**Comment by finestructure** [comment] 2022-08-23 09:57
While it works for stdout it doesn't seem to be working for stderr (despite redirect):

<img width="773" alt="CleanShot 2022-08-23 at 11 56 00@2x" src="https://user-images.githubusercontent.com/65520/186129511-1d35dba8-2100-4ca9-845a-f83d487fa0ed.png">

Also, the build command return value isn't being passed through because we're throwing from within the build command. So we won't receive the command in the error case this way.

**Comment by finestructure** [comment] 2022-08-24 09:26
Ok, I think I've got this fixed now (build command reporting and linux error logs): https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/143

**Comment by finestructure** [comment] 2022-08-25 07:29
That took way longer than planned 😅 but it's fixed now, alongside a few other pesky issues:

https://swiftpackageindex.com/builds/06D90276-3861-4661-975C-7C2EC6340655

<img width="797" alt="CleanShot 2022-08-25 at 09 28 10@2x" src="https://user-images.githubusercontent.com/65520/186602646-df08e78a-5595-420e-b0fe-8678ec3e949e.png">

**Closed by finestructure** 2022-08-25 07:29 UTC
Labels: bug

**Comment by mattmassicotte** [comment] 2022-08-26 10:27
You figured it out! What a journey. Thanks so much!
