### ISSUE TITLE
Failure to build a package if its `swift-tools-version` is 6.0

### ISSUE THREAD

**Issue by millenomi** [SwiftPackageIndex/SwiftPackageIndex-Server#3529] opened 2024-11-28 01:00 UTC
**Please describe the bug**

My UIElements package (at <https://github.com/noeticgarden/uielements>) failed to build in SPI despite building correctly at-desk and in internal CI. It appears that some build flags are trying to force on Swift 6 features, which are already on for Swift 6.

The tag that triggered the problem is 0.1.0, at: <https://github.com/noeticgarden/uielements/tree/0.1.0>. The builds of that tag (like e.g. <https://swiftpackageindex.com/builds/2CEA997C-68C3-4696-8E81-118838919CC1>) all have the following errors:

```
<unknown>:0: error: upcoming feature 'StrictConcurrency' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'DisableOutwardActorInference' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'GlobalActorIsolatedTypesUsability' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'InferSendableFromCaptures' is already enabled as of Swift version 6
```

**Explain the steps needed to reproduce the bug**

1. Attempt to build or update <https://github.com/noeticgarden/uielements/tree/0.1.0> on SPI.

**What was the expected behaviour?**

The project should build correctly and without forcing the indicated flags, since they are already on for that package.

**Comment by finestructure** [comment] 2024-11-28 07:16
Thanks for the report, @millenomi ! That's bad, looking into how to best address this.

**Comment by mattmassicotte** [comment] 2024-11-28 11:03
Ugh yes. You cannot unconditionally apply these to packages which use 6.0 tools…

Not that this helps right now, but: https://forums.swift.org/t/downgrade-upcoming-feature-is-already-enabled-error-to-a-warning/75762

**Comment by lukepistrol** [comment] 2024-11-28 12:29
I was just about to file a bug as well, then saw this.

Happening [here](https://swiftpackageindex.com/lukepistrol/TaskTrigger/builds) too.

**Comment by finestructure** [comment] 2024-11-28 17:09
I have a fix for this but I still need to clean some things up. Should go live tomorrow and then I'll see how I can identify affected builds and retrigger them.

**Comment by finestructure** [comment] 2024-11-29 08:58
I've deployed a builder that fixes this issue and re-triggered all builds of packages with tools-version 6.0. This does not yet cover the case where the tools-version is 5.x and the manifest sets language version 6 - for that we need to deploy a change gathering that data which I'll prepare shortly.

**Comment by finestructure** [comment] 2024-11-29 12:08
Turns out we had that data already, I just didn't know it 😅 All tools version 6 or language version 6 builds are now retriggered and should be rebuilt over the coming days as we run through the latest Swift 6 preview build.

**Comment by finestructure** [comment] 2024-12-01 10:45
I screwed up when suppressing the Swift 6 flags. I accidentally _also_ suppressed the arguments which write out the JSON we use to report the results 🤦‍♂️

```
env DEVELOPER_DIR=/Applications/Xcode-16.1.0.app xcrun swift build --arch arm64
```

Need to fix this and re-run the affected builds.

**Comment by finestructure** [comment] 2024-12-02 16:55
Fixed and deployed as builder 4.58.3, affected builds re-triggered.

**Comment by finestructure** [comment] 2024-12-03 07:18
Linux build for swift-sharing still failing with the flags error - despite working running locally. It’s bizarre. This is running in a docker image, so it’s hard to see how this could behave differently.

https://swiftpackageindex.com/builds/42F71B62-0528-438C-8DB2-A68FE9FD7990

```
========================================
RunAll
========================================
Builder version: 4.58.3
Interrupt handler set up.
========================================
Checkout
========================================
Clone URL: https://github.com/pointfreeco/swift-sharing.git
Reference: main
…
[129/130] Compiling ConcurrencyExtras UncheckedSendable.swift
<unknown>:0: error: upcoming feature 'StrictConcurrency' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'DisableOutwardActorInference' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'GlobalActorIsolatedTypesUsability' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'InferSendableFromCaptures' is already enabled as of Swift version 6
BUILD FAILURE 6.0 linux
```

**Comment by finestructure** [comment] 2024-12-03 08:35
Ok, I understand what's going on now. This is how we extract build info from the manifest:

```swift
    static func includeSwift6Flags(at path: String) async -> Bool {
        struct PackageManifest: Decodable {
            var swiftLanguagesVersions: [String]?
            var toolsVersion: String
        }
        do {
            let json = try await Current.shell.run(command: .swiftPackageDescribe, at: path)
            let manifest = try JSONDecoder.convertingFromSnakeCase.decode(PackageManifest.self, from: Data(json.utf8))
            return includeSwift6Flags(toolsVersion: manifest.toolsVersion, languageVersions: manifest.swiftLanguagesVersions)
        } catch {
            print("Failed to describe package manifest: \(error)")
            return true
        }
    }
```

On linux, the builder is a docker image with the builder binary which in turn runs a docker command to build the package with another image for the specific Swift version.

Host → [container `registry.gitlab.com/finestructure/swiftpackageindex-builder:4.58.3`] → [container `registry.gitlab.com/finestructure/spi-images:basic-6.0-latest`]

The builder image itself does _not_ include Swift - unlike all the Apple builders, which do come with Xcode. So `swift package describe`, which runs in the builder container prior to launching the build, actually fails and defaults to `true`.

My local test of the linux build is imperfect - it doesn't run the builder docker image (that would be really hard to set up in a unit test). It only launches the inner build test with the `spi-images` container.

A temporary workaround is probably to build `swiftpackageindex-builder` based on `swift:6.0.2-jammy` instead of just `ubuntu:jammy`. It's not ideal because this Swift version would serve _all_ Linux builds, i.e. also Swift versions < 6.0, but that's unavoidable here and since all we do is `package describe` ok if temporary.

We really need that [fix where redundant flags don't fail the build](https://forums.swift.org/t/downgrade-upcoming-feature-is-already-enabled-error-to-a-warning/75762) so we can remove this workaround.

**Comment by finestructure** [comment] 2024-12-03 09:46
Linux builds are now passing:

<img width="754" alt="Screenshot 2024-12-03 at 10 45 21" src="https://github.com/user-attachments/assets/c2f07d82-f981-4981-9d00-a9be60172e77">

I've retriggered all 983 Linux builds with language mode 6 or tools version 6.

**Comment by finestructure** [comment] 2024-12-04 08:45
This issue keeps on giving. I'm _still_ seeing failures with the latest build even on macOS. For example the [macos-spm build](https://swiftpackageindex.com/builds/A1098D24-4DA7-4EE3-97B0-050AA1C4D3F6) in https://swiftpackageindex.com/sindresorhus/Defaults/builds

```
[27/56] Emitting module SwiftSyntax600
<unknown>:0: error: upcoming feature 'StrictConcurrency' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'DisableOutwardActorInference' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'GlobalActorIsolatedTypesUsability' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'InferSendableFromCaptures' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'StrictConcurrency' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'DisableOutwardActorInference' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'GlobalActorIsolatedTypesUsability' is already enabled as of Swift version 6
<unknown>:0: error: upcoming feature 'InferSendableFromCaptures' is already enabled as of Swift version 6
BUILD FAILURE 6.0 macosSpm
```

The package's tools version is 5.11 and there's no explicit language mode 6 set. That's why our detection and flag suppression is failing. I suspect the issue is that the `.package(url: "https://github.com/swiftlang/swift-syntax", from: "600.0.1")` dependency is setting it and _that's_ what's causing the error.

If so, I don't think there's anything we can do here, other than adding a per-package override. We can't really start crawling the whole dependency tree to find language mode 6 settings.

Re-opening issue just to confirm this is the problem.

**Comment by finestructure** [comment] 2024-12-04 09:37
Yes, Swift Syntax is configuring language mode 6 in its manifest:

```
  swiftLanguageVersions: [.v5, .version("6")]
```

There's nothing we can do here until [redundant flags don't fail the build](https://forums.swift.org/t/downgrade-upcoming-feature-is-already-enabled-error-to-a-warning/75762).

**Comment by finestructure** [comment] 2024-12-04 09:39
Actually, there is something we can do - add specific exceptions. Since Swift Syntax is probably a rather common dependency this is something we should do for now. I'll prep this in a way that it can be a dynamic setting.

**Closed** 2024-12-05 09:14 UTC
Labels: bug
