### ISSUE TITLE
Xcode and SPM builds issues with spi.yml scheme

### ISSUE THREAD

**Issue by MortenGregersen** [SwiftPackageIndex/SwiftPackageIndex-Server#1633] opened 2022-03-22 21:04 UTC
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/MortenGregersen/Bagbutik

**Please explain what data is incorrect and what you expected to see**

In my package I have 2 products: "Bagbutik" (the library) and "bagbutik" (the CLI).

In the repository I have a `.spi.yml` file with the following contents:

```yaml
version: 1
builder:
  configs:
  - platform: macos-xcodebuild
    scheme: Bagbutik
  - platform: macos-xcodebuild-arm
    scheme: Bagbutik
  - platform: ios
    scheme: Bagbutik
  - platform: tvos
    scheme: Bagbutik
  - platform: watchos
    scheme: Bagbutik
```

I expect, that the builders will only build the "Bagbutik" scheme.

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

In this build, we can see that it also builds the "BagbutikCLI" target and "BagbutikGenerator" target:
- https://swiftpackageindex.com/builds/551BA916-FE7E-4F4B-BF88-E9264CA9D5E3

**Screenshots**

![CleanShot 2022-03-22 at 22 03 33](https://user-images.githubusercontent.com/759680/159575716-3eb0375d-dbf1-47aa-91be-8fdb6a7f2527.png)

**Comment by finestructure** [comment] 2022-03-23 04:21
Thanks for reporting this, Morten!

So this is tricky, there are two related issues at play here:

- `.spi.yml`'s scheme directives are only applied for Xcode builds, not for SPM builds
- Xcode builds fail despite the `.spi.yml` scheme directive, because package resolution fails

The first issue we could theoretically work around by extending the mechanism to SPM. There are two SPM build flags that look promising: `swift build --target <...>` and `swift build --product <...>`. However, both of these fail with the same error for your package:

```
❯ env DEVELOPER_DIR="/Applications/Xcode_13.2.1.app" xcrun swift build --arch arm64 --target Bagbutik
Updating https://github.com/shibapm/Komondor.git
< ... snip ... >
Computing version for https://github.com/apple/swift-docc-plugin
error: Dependencies could not be resolved because root depends on 'swift-docc-plugin' 1.0.0..<2.0.0.
'swift-docc-plugin' >= 1.0.0 cannot be used because no versions of 'swift-docc-plugin' match the requirement 1.0.1..<2.0.0 and 'swift-docc-plugin' 1.0.0 contains incompatible tools version (5.6.0).
```

So even if we made that change it wouldn't help. Unfortunately, I don't see a way to build your package with Swift 5.5 via SPM.

Now, your package _is_ usable from Swift 5.5. I've created a test package and added it as a dependency referencing the `Bagbutik` product and this works. The problem is that our build system doesn't work that way :(

The problem with the Xcode builds is that we run `xcodebuild -resolvePackageDependencies` in order to discover the project's schemes. This fails for your package with the same error it does for the SPM build:

```
'swift-docc-plugin' >= 1.0.0 cannot be used because no versions of 'swift-docc-plugin' match the requirement 1.0.1..<2.0.0 and 'swift-docc-plugin' 1.0.0 contains incompatible tools version (5.6.0).
```

I _think_ we could actually avoid running package resolution in case we are provided a scheme via `.spi.yml` but I need to double check if we perhaps run it for other reasons as well.

So I think the situation is the following:

- The SPM builds are going to be really hard to recover.
- The Xcode builds we can probably recover (to be confirmed).

If the Xcode build passes with Swift 5.5 the matrix will show macOS and 5.5 support even though the SPM builds fail due to the way we aggregate the results up from the full build details.

That's not ideal but I think it'll get us the result we want, at least on the package page.

Now we've also discussed extending `.spi.yml` to allow authors to opt out of certain build results. What this would allow you to do is say: "don't build for SPM/5.5" and then we wouldn't show them as failed but rather skipped or so. This would get us most of the way there.

We're also in the process of adding support for Swift 5.6. While that won't fix the 5.5 box at least it'll help with the platform support part of the matrix.

- [ ] check if we can skip `xcodebuild` package resolution when we're given a custom scheme via `.spi.yml`

**Comment by MortenGregersen** [comment] 2022-03-23 09:55
Thank you for the investigation, @finestructure!

I saw the same problem with swift-docs-plugin yesterday, and removed it, as the documentation is generated with Jazzy now. It was merged a couple of hours before your post here: https://github.com/MortenGregersen/Bagbutik/pull/69

It looks like the same problem occurs on Linux: https://swiftpackageindex.com/builds/448FE75C-98D5-4F33-982F-6A9D995F4BB5

**Comment by finestructure** [comment] 2022-03-23 11:11
Yes, Linux is affected the same way as the macOS SPM builds.

**Comment by MortenGregersen** [comment] 2022-03-23 20:39
But with the dependency requiring Swift 5.6 removed, don't you think, that the solution with `swift build --target <...>` and `swift build --product <...>` would work?

**Comment by finestructure** [comment] 2022-03-24 08:23
Yes, `--target` seems to work. (`--product` doesn't, for reasons that aren't clear to me but we could just use `--target`):

```
❯ env DEVELOPER_DIR="/Applications/Xcode_13.2.1.app" xcrun swift build --arch arm64 --target Bagbutik
[869/869] Build complete!
❯ env DEVELOPER_DIR="/Applications/Xcode_13.2.1.app" xcrun swift build --arch arm64 --product Bagbutik
warning: '--product' cannot be used with the automatic product 'Bagbutik'; building the default target instead
/Users/sas/Projects/SPI/spi-builder/checkout/Sources/BagbutikCLI/BagbutikCLI.swift:11:1: error: 'BagbutikCLI' is annotated with @main and must provide a main static function of type () -> Void or () throws -> Void.
@main
^
```

**Comment by finestructure** [comment] 2022-03-24 08:26
The error message also implies that SPM determines a "default target" somehow. There doesn't seem to be any way to influence that though. For instance, `BagbutikCLI` isn't the first target, which might have indicated that simply putting the `Bagbutik` target first could have fixed it without further intervention.

**Comment by finestructure** [comment] 2022-03-24 08:29
- [ ] make SPM builds respect `.spi.yml` scheme settings via the `--target` flag

**Comment by finestructure** [comment] 2022-03-24 08:54
> * check if we can skip `xcodebuild` package resolution when we're given a custom scheme via `.spi.yml`

This doesn't actually make a difference: the build fails later anyway with the exact same error even if we push package resolution back.

**Comment by finestructure** [comment] 2022-03-24 10:16
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/98

**Comment by finestructure** [comment] 2022-03-24 13:48
This is now deployed and the SPM should turn green once you merge https://github.com/MortenGregersen/Bagbutik/pull/72 @MortenGregersen 

I've tested this on my fork so it should all go smoothly :) Please re-open the issue if you're still having trouble!

**Comment by MortenGregersen** [comment] 2022-03-25 21:52
It looks like it still tries to build the CLI on Linux: https://swiftpackageindex.com/builds/941880A7-31EE-42C8-92B5-B7FFAAE4D24E

```
[371/581] Compiling BagbutikCLI BagbutikCLI.swift
/host/spi-builder-workspace/Sources/BagbutikCLI/BagbutikCLI.swift:11:1: error: 'BagbutikCLI' is annotated with @main and must provide a main static function of type () -> Void or () throws -> Void.
@main
^
```

**Comment by finestructure** [comment] 2022-03-26 08:25
Thanks for spotting this, Morten! The fix is up and will be deployed soon. I'll keep this issue open until we've deployed and re-run the builds for Bagbutik.

**Comment by finestructure** [comment] 2022-03-26 09:37
<img width="734" alt="CleanShot 2022-03-26 at 10 36 55@2x" src="https://user-images.githubusercontent.com/65520/160233753-33e25e76-668f-4f24-9484-973d2f4419bf.png">

:)

**Closed by finestructure** 2022-03-26 09:37 UTC
Labels: package data
