### ISSUE TITLE
Don't report "no dependencies" without dependency info (all builds fail)

### ISSUE THREAD

**Issue by kelvin13** [SwiftPackageIndex/SwiftPackageIndex-Server#1593] opened 2022-02-28 00:11 UTC
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/kelvin13/swift-json

according to the site, [`swift-json`](https://github.com/kelvin13/swift-json) has no dependencies. this is not true, as `swift-json` [depends](https://github.com/kelvin13/swift-json/blob/af99abf69556f0fda6648251873de1a4a2da9ac0/Package.swift) on [`swift-grammar`](https://github.com/kelvin13/swift-grammar). 

`swift-grammar` is an inline-only module, and both modules are pure-swift libraries, but still, this seems inaccurate

**Comment by finestructure** [comment] 2022-02-28 07:24
Thanks for the report, @kelvin13 ! We're using the `Package.resolved` output of our build system to report back a package's dependencies and the problem is that your package is using 5.6 and fails all of our builds.

We should be able to detect having not received any dependency information (vs having received info about no dependencies) and update the display accordingly (probably just by omitting dependency info in that case).

I'll rename the issue accordingly, thanks again for reporting it!

**Comment by kelvin13** [comment] 2022-02-28 23:20
`swift-json` got a new release this morning that adds support for 5.3, 5.4, and 5.5. it looks like the index page is showing the right information now!

**Comment by finestructure** [comment] 2022-03-02 14:38
I've just tested this locally: we are omitting the "dependencies" entry if `resolved_dependencies` is `NULL`. That means in that case, the builder must have reported an empty array back. Need to check why/how that could have happened here.

**Comment by finestructure** [comment] 2022-03-02 14:48
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/97

**Comment by finestructure** [comment] 2022-03-02 17:31
Deployed

**Closed by finestructure** 2022-03-02 17:31 UTC
Labels: package data
