### ISSUE TITLE
URL generation from routing

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#172] opened 2020-05-27 06:22 UTC
With the Vapor router not being able to generate URLs for routes, we should implement our own URL generation mechanism. It doesn't need to be super generic, or complex, but we do need a *central* source of generating URLs to pages in the site.

For now, this could be as simple as a few static funcrions:

* `urlForHomePage(relative: Bool)`
* `urlForAboutPage`
* `urlForFAQPage`
* `urlForPrivacyPolicyPage(relative: Bool)`
* `urlForPublicPackagePage(relative: Bool)`

The about page, FAQ page, and other functions that don't include a `relative` flag should always be fully qualified URLs as they are going to be off-site links for this launch version. 

Did I miss any URLs that we need to generate?

**Comment by finestructure** [comment] 2020-05-27 06:39
Duplicate of #109? Can probably close one of them.

**Closed** 2020-06-02 09:00 UTC
