### ISSUE TITLE
Incorrect Dependency Count

### ISSUE THREAD

**Issue by Sherlouk** [SwiftPackageIndex/SwiftPackageIndex-Server#2214] opened 2023-01-10 13:46 UTC
**Please describe the bug**

I've noticed that the listed dependency count on [my package](https://swiftpackageindex.com/getsidetrack/swift-device-authority) is less than the real amount.

SPI is saying it has no dependencies, but it has 2 direct (3 indirect) dependencies which are noted in the [resolved file](https://github.com/getsidetrack/swift-device-authority/blob/main/Package.resolved).

**What was the expected behaviour?**

I'd expect SPI to say that the package has 3 dependencies.

**Screenshots**

![image](https://user-images.githubusercontent.com/15193942/211567835-c8feeadf-d30f-401a-a341-a6a1e622bc69.png)

**Additional context**

https://github.com/getsidetrack/swift-device-authority

**Comment by finestructure** [comment] 2023-01-23 10:15
I suspect this has something to do with what target has the dependencies:

```swift
        .target(
            name: "DeviceAuthority",
            dependencies: []
        ),
```

vs

```swift
        .executableTarget(
            name: "CommandLine",
            dependencies: [
                .product(name: "ConsoleKit", package: "console-kit"),
                .product(name: "ShellOut", package: "ShellOut"),
            ]
        ),
```

There's an argument to be made that zero is the correct count from the perspective of a developer using the package as a dependency. It will not bring in any transient dependencies. (It may still be a bug that we find zero here and it just so happens to also make sense, see below.)

There's the other angle where supply-chain attacks can happen via _any_ dependency, whether they're actually used to build a product or just as a dev tool. In this scenario the count should be three (essentially the count in `Package.resolved`).

I need to check but I _thought_ that's what we're reporting.

**Comment by finestructure** [comment] 2023-01-23 16:47
Ok, I know what the problem is. Some recent Swift version (I believe 5.6) brought a new `Package.resolved` format (version 2) and we're using a `Decodable` implementation that can't read this.

**Comment by finestructure** [comment] 2023-01-23 16:47
The point I raised above about target dependencies and all dependencies is something we'll address once we look into more detailed dependency analysis.

**Comment by finestructure** [comment] 2023-01-24 10:50
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/171, should be deployed shortly.

**Closed by finestructure** 2023-01-24 10:50 UTC
Labels: bug, package data
