### ISSUE TITLE
Feature request: dependencies

### ISSUE THREAD

**Issue by kkk669** [SwiftPackageIndex/SwiftPackageIndex-Server#730] opened 2020-09-30 16:40 UTC
I wish Swift Package Index could show dependencies of a package as [Swift Package Registry](https://swiftpackageregistry.com/apple/swift-package-manager) does. It helps find a package that has less dependencies.

**Comment by daveverwer** [comment] 2020-09-30 20:27
Thanks for the suggestion Kenta! This feature request is already on the list and is being tracked as #307. I'll close this as a duplicate of that. Thanks again!

**Closed by daveverwer** 2020-09-30 20:27 UTC

**Comment by kkk669** [comment] 2020-10-01 00:13
I'm sorry, I missed that. Thanks!
