### ISSUE TITLE
Incorrectly showing that lottie-ios package doesn't support Swift 5.5

### ISSUE THREAD

**Issue by calda** [SwiftPackageIndex/SwiftPackageIndex-Server#2225] opened 2023-01-19 18:19 UTC
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/airbnb/lottie-ios

**Please explain what data is incorrect and what you expected to see**

Lottie supports Swift 5.5 / Xcode 13.2.1. We verify this with a CI job that builds the package using Xcode 13.2.1 / Swift 5.5.2, which passes on master / the latest release: https://github.com/airbnb/lottie-ios/actions/runs/3651050872/jobs/6167800054

The index reports the Swift 5.5 / Xcode 13.2.1 build as failing [here](https://swiftpackageindex.com/builds/94191B25-8497-4A69-9E9C-63BF02D044C7), but I can't tell why. It just says `Build command unavailable` so I'm not sure how to reproduce this failure.

The error is:

```
xcodebuild: error: Could not resolve package dependencies:
  Package.resolved file is corrupted or malformed; fix or delete the file to continue: unsupported schema version 2
```

but I'm not sure what that means, and we don't run in to this issue in our Xcode 13.2.1 CI job above. Any clue what this means?

**Comment by daveverwer** [comment] 2023-01-19 18:29
Yea that's an odd error. I think what I'll do first of all before we investigate further is kick off a fresh set of builds for Swift 5.5.  I'll report back shortly.

**Comment by daveverwer** [comment] 2023-01-19 18:48
OK, so the build failed again with the same error and I also tried running the build command manually on that same runner machine (which is the only machine I have access to that can still run Xcode 13 😬) and got the same error there, too.

The command it's running which fails is:

```
$ /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=/Users/builder/Desktop/checkout/.dependencies -resolvePackageDependencies
```

and the result is:

```
objc[61115]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1dcc6b838) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c2c8). One of the two will be used. Which one is undefined.
objc[61115]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1dcc6b888) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c318). One of the two will be used. Which one is undefined.
objc[61115]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1dcc6b650) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c598). One of the two will be used. Which one is undefined.
objc[61115]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1dcc6b6a0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c5e8). One of the two will be used. Which one is undefined.
objc[61115]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1dcc6b6f0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c638). One of the two will be used. Which one is undefined.
objc[61115]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1dcc6b740) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c688). One of the two will be used. Which one is undefined.
objc[61115]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1dcc6b790) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c6d8). One of the two will be used. Which one is undefined.
objc[61115]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1dcc6b7e0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10836c728). One of the two will be used. Which one is undefined.
Command line invocation:
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=/Users/builder/Desktop/checkout/.dependencies -resolvePackageDependencies

User defaults from command line:
    IDEClonedSourcePackagesDirPathOverride = /Users/builder/Desktop/checkout/.dependencies
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph
Package.resolved file is corrupted or malformed; fix or delete the file to continue: unsupported schema version 2xcodebuild: error: Could not resolve package dependencies:
  Package.resolved file is corrupted or malformed; fix or delete the file to continue: unsupported schema version 2
```

Can you reproduce that locally, too?

**Comment by finestructure** [comment] 2023-01-19 19:06
The problem is that there’s a version 2 `Package.swift` file checked in, which trips up our build command:

https://github.com/airbnb/lottie-ios/blob/master/Lottie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Dave, deleting this file should make the build pass.

Not sure why it doesn’t fail for you in CI, Cal. The `IDEClonedSourcePackagesDirPathOverride` wouldn’t be a problem, that just ensures that all dependencies are saved inside the build directory rather than some global cache (derived data) which would clog up our build machines after a while.

**Comment by calda** [comment] 2023-01-19 19:13
Thanks! I regenerated that file by deleting it and running `/Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies` and that command succeeds now.

Interestingly I'm able to run that command on macOS 13.1 even though Xcode 13.2.1 isn't technically supported. Convenient!

**Comment by calda** [comment] 2023-01-19 19:59
I think this wasn’t failing in CI for us because these dependencies are only for the test target and not the actual package. So building just the package doesn’t require resolving the dependencies.

**Comment by calda** [comment] 2023-01-19 23:33
Fixed now 👍🏻 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/1811727/213585445-77a0f9ee-d79a-4e02-85fa-b8f97e519869.png">

**Comment by finestructure** [comment] 2023-01-20 05:16
🎉 I'll go ahead and close this then. Please reopen if there are any further issues!

**Closed** 2023-01-20 05:17 UTC
Labels: package data
