### ISSUE TITLE
Incorrect package data for grpc-swift

### ISSUE THREAD

**Issue by glbrntt** [SwiftPackageIndex/SwiftPackageIndex-Server#3292] opened 2024-08-15 09:54 UTC
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/grpc/grpc-swift/

**Please explain what data is incorrect and what you expected to see**

The last changes to the default branch (`main`) are showing as 21 days ago. It has had almost daily changes since then.

This is also reflected in the build status: the last builds for the default branch were on 24th July.

The Swift 6.0 beta builds are also showing as "Pending" and have done over the last few days when I've checked.

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

N/a

**Screenshots**

N/a

**Additional context**

- W.r.t. Swift 6, the package does have a version specific manifest: `Package@swift-6.swift`.
- One change we made soon after the last reported main builds was to change from `swiftLanguageVersion` to `swiftLanguageMode` (https://github.com/grpc/grpc-swift/commit/0aad7094c3f3c973b7dee92c05b8fa64a5c29177) in the Swift 6 manifest. It may or may not be related (it looks like your Swift 6 builder image is currently new enough to handle `swiftLanguageMode`)

**Comment by daveverwer** [comment] 2024-08-15 09:56
Thanks for the report, @glbrntt! This is likely a duplicate of #3290, which we found yesterday and is being investigated.

I'll leave this open but wanted to tag that issue so they can be related.

**Comment by daveverwer** [comment] 2024-08-15 10:22
Actually I just realised I didn't address this point:

> The Swift 6.0 beta builds are also showing as "Pending" and have done over the last few days when I've checked.

This is something different and it's intentional, or at least unavoidable for now.

We are running all packages past every iteration of the Swift 6 beta as part of our [Ready for Swift 6 project](https://swiftpackageindex.com/ready-for-swift-6). With the pace of Xcode releases during the summer, we almost always have a very large queue of pending builds as it takes more than 7 days for us to process everything for a new Xcode version.

This is unrelated to the analysis process that updates new versions and other metadata and is not affecting this issue.

**Comment by glbrntt** [comment] 2024-08-15 11:48
How about Linux, would those builds be done at the same time as the Xcode builds?

Relatedly, is the documentation built at the same time? We added a new documentation target which is Swift 6 only whose docs haven't appeared yet.

**Comment by finestructure** [comment] 2024-08-15 11:57
The Swift 6 Linux builds are scheduled at the same time, yes.

Note that your documentation is currently configured to be run with the latest _release_ version of Swift (i.e. you're using the defaults). So if one of your targets requires Swift 6 (via the tools-version) then your documentation build on 5.10 will not be able to generate the docs for it.

I've opened a PR to move doc gen to Swift 6 here: https://github.com/grpc/grpc-swift/pull/2019

**Comment by glbrntt** [comment] 2024-08-15 12:18
Oh that's great, thanks very much!

**Comment by finestructure** [comment] 2024-08-21 08:20
This has now been updated:

![CleanShot 2024-08-21 at 10 19 49@2x](https://github.com/user-attachments/assets/1f22404a-9ba5-4ad3-af90-ebc60eae45b2)

**Closed by finestructure** 2024-08-21 08:20 UTC
Labels: package data

**Comment by glbrntt** [comment] 2024-08-22 07:11
Thanks Sven and Dave!
