### ISSUE TITLE
BlueConnect data race safety errors reported

### ISSUE THREAD

**Issue by danielepantaleone** [SwiftPackageIndex/SwiftPackageIndex-Server#3456] opened 2024-10-26 14:08 UTC
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/danielepantaleone/BlueConnect

**Please explain what data is incorrect and what you expected to see**

The package is reported having Swift 6 data race safety errors. Inspecting the full build result, Swift 6 data race errors are reported (11) but I couldn't find any hint in the [build logs](https://swiftpackageindex.com/builds/E7F4B51A-7582-47F0-9330-507F2BEA9346).

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

- https://swiftpackageindex.com/builds/E7F4B51A-7582-47F0-9330-507F2BEA9346
- https://swiftpackageindex.com/builds/FB02A919-F852-4734-A657-5545171F71C7
- https://swiftpackageindex.com/builds/3822FA4B-B0B4-47C9-BAE6-87B4F6A979B7
- https://swiftpackageindex.com/builds/9D7BABEF-7BD5-4961-991D-A19440B8B2C6
- https://swiftpackageindex.com/builds/2F1D65D2-E0AA-460D-9B65-8B5F77FB19F8
- https://swiftpackageindex.com/builds/BF73AAB4-D9EE-444D-9589-9877B3F0DF92

I also tried to run the same xcodebuild command in my local setup and no error or warning is produced.

**Screenshots**

---

<img width="842" alt="Screenshot 2024-10-26 at 16 05 06" src="https://github.com/user-attachments/assets/4e42e1d7-60a3-4a68-a576-594d1eaad8a9">

---

<img width="596" alt="Screenshot 2024-10-26 at 16 05 19" src="https://github.com/user-attachments/assets/d5894cef-db52-4cd5-8386-fdf3e1e8ab0c">

**Comment by finestructure** [comment] 2024-10-26 15:08
Thanks for the report @danielepantaleone ! This is very likely a duplicate of #3233. I'll close this for now, to be reviewed once there is a fix for the known false negatives.

**Closed** 2024-10-26 15:08 UTC
Labels: package data

**Comment by danielepantaleone** [comment] 2024-10-26 15:44
My bad, I tried to search for an already open issue, but I could find #3233. Thanks anyway!

**Comment by finestructure** [comment] 2024-10-26 15:50
No problem at all, it's good to hear about affected packages so we get a feel for how widespread the issue is!
