### ISSUE TITLE
Old Alamofire builds are incorrect

### ISSUE THREAD

**Issue by jshier** [SwiftPackageIndex/SwiftPackageIndex-Server#927] opened 2021-02-12 17:05 UTC
It seems that there have been improvements to the SPI build process which make it more successful for Alamofire. The Alamofire `master` builds appear correct for compatibility, but the 5.4.1 tag does not. Can those tag builds be redone with the newer build logic?

**Comment by daveverwer** [comment] 2021-02-12 17:30
It looks like all those builds failed because the build command couldn't be generated, and looking at a couple of the logs it's because it couldn't find a scheme for them. My memory says we fixed that *way* before 5.4.1 was released, but my memory is often wrong.

We can, of course, clear the 5.4.1 builds out and it will re-build, but I'd also like to understand the situation a bit better as I thought we cleared out most of the failed builds that were caught on this problem. It'd be good to get a sense of whether this is a widespread problem. I fear it might be, and I also know that the solution is potentially a very painful few weeks of reprocessing failed builds.

I'm sure @finestructure will have something to say on it too. He's also likely to remember when we fixed the issue better than I do.

Thanks for reporting it Jon.

**Comment by finestructure** [comment] 2021-02-12 18:03
I need to look into this in more detail but I think the problem is that the default scheme isn't working. Early on we actually added special handling for Alamofire (before we added `.spi.yml`) in our builder:

```swift
            case ("https://github.com/Alamofire/Alamofire.git".lowercased(), _):
                return [.init(platform: .watchos, scheme: "Alamofire watchOS")]
```

As you can see, that works: https://swiftpackageindex.com/builds/BA9CBDC1-2E4F-4662-AFA0-17B0B4C6C6AD

What's odd is that `master` is building but I guess there might be differences in how the project is set up between versions?

Would it be feasible for you to add a `.spi.yml` to configure the correct schemes for the old version?

**Comment by jshier** [comment] 2021-02-12 18:05
How would I add that file to an existing tag without changing the tag in some way? I suppose I could add it on the `master` branch, but that branch seems to be working fine. And no, there haven't been project changes between the two.

**Comment by finestructure** [comment] 2021-02-12 18:10
Yeah, you couldn't really - it'd have to be a new tag and that's surely not a good enough reason. Let me investigate the real cause first and then we can see if we patch up the special casing for now. (Although that's also not ideal - I'd already forgotten that we even to that and it might lead to surprising results in the future.)

**Comment by jshier** [comment] 2021-02-12 18:13
There's only a single PR difference between 5.4.1 and `master` and that was a test refactoring that didn't change how the project was organized, just how our tests work (we now use a local server to test requests).

**Comment by finestructure** [comment] 2021-02-12 19:29
Interesting. I'll definitely start by re-running the tests but as far as I recall there weren't any build logic changes since 5.4.1 (from Dec 21). Let's see what happens when I reset them!

**Comment by finestructure** [comment] 2021-02-15 09:06
Turns out the build works with the current builder and 5.4.1. I've reset the 5.4.1 builds and they should hopefully come back green soon.

I'll keep this open until it's confirmed, thanks again for reporting it, Jon.

**Comment by finestructure** [comment] 2021-02-15 09:09
Just had a look through the builder history and there was indeed one change, on Jan 11, that might have been relevant: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/873

**Comment by finestructure** [comment] 2021-02-15 11:14
We’re in the green now, closing:

![98E1E16C-1DF0-4E0A-8A98-79531D5752B0](https://user-images.githubusercontent.com/65520/107939632-4beca480-6f87-11eb-94f4-25916424b433.jpeg)

**Closed by finestructure** 2021-02-15 11:14 UTC

**Comment by jshier** [comment] 2021-02-15 15:07
Thanks!
