### ISSUE TITLE
Conditionally adding the DocC plugin is failing

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#3215] opened 2024-07-12 17:21 UTC
Since the rename of `apple` to `swiftlang`, it looks like we can now fail when detecting the DocC plugin:

```
error: 'spi-builder-workspace': 'spi-builder-workspace' dependency on 'https://github.com/apple/swift-docc-plugin' conflicts with dependency on 'https://github.com/swiftlang/swift-docc-plugin' which has the same identity 'swift-docc-plugin'
```

https://swiftpackageindex.com/builds/6A922B06-15B4-49E9-A414-CA3970020851

**Comment by finestructure** [comment] 2024-07-12 17:35
Ah, that's probably also the cause of #3201

**Comment by finestructure** [comment] 2024-07-16 07:26
Does not appear to be realted to #3201 after all.

**Comment by finestructure** [comment] 2024-07-16 09:39
Fixed in https://gitlab.com/finestructure/swiftpackageindex-builder/-/merge_requests/298 (not yet deployed)

**Closed** 2024-07-16 11:06 UTC
Labels: bug
