### ISSUE TITLE
SoulverCore readme not loading

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1628] opened 2022-03-18 14:03 UTC
https://swiftpackageindex.com/soulverteam/SoulverCore

![image](https://user-images.githubusercontent.com/65520/159017201-288f7b2c-b143-4838-951a-f4ae2e2f5a85.jpeg)

**Comment by daveverwer** [comment] 2022-03-21 16:06
I've looked into this and I know what's happening... I just don't know why it's happening!

So, until #1095 is done, we're loading this README by parsing the HTML of the README page that GitHub renders. For most README files, the markdown is rendered down to HTML on the README page we're fetching. Like this one for the [Alamofire README](https://github.com/Alamofire/Alamofire/blob/master/README.md):

<img width="881" alt="Screenshot 2022-03-21 at 15 12 28@2x" src="https://user-images.githubusercontent.com/5180/159291567-71ed9681-7362-49ae-9a9e-93ed13ba4a0e.png">

Whereas with the [SoulverCore README](https://github.com/soulverteam/SoulverCore/blob/master/README.md) it's rendering it as source code:

<img width="881" alt="Screenshot 2022-03-21 at 16 01 33@2x" src="https://user-images.githubusercontent.com/5180/159301353-865649a2-c0f3-40b6-ace2-3e83b1a81505.png">

I have a hunch this may be because the file begins with some HTML tags rather than Markdown, but who knows! I'll run a test on Leftpad on this. 

A better way to fix it might be to implement #1095, but that's not trivial as we need to cache those README responses so as not to run out of API requests.

**Comment by daveverwer** [comment] 2022-03-22 14:50
Closing this for now as I wasn't able to reproduce this issue on other repos and so it's possible it's something specific to this repository. 

The error message means people are no longer abandoned and now get a link to the README.

**Closed by daveverwer** 2022-03-22 14:50 UTC
Labels: bug
