### ISSUE TITLE
Display on a package page that it is archived

### ISSUE THREAD

**Issue by mackoj** [SwiftPackageIndex/SwiftPackageIndex-Server#806] opened 2020-11-23 17:15 UTC
Hi,

Thanks for making the index.

It would be great if we could see on a Package page if it is archived.
Like this one for example https://github.com/Fitzafful/BillboardSwiftLibrary.

Thanks,

**Comment by Sherlouk** [comment] 2020-11-23 18:06
Thanks for the suggestion Jeffrey!

I believe this is a duplicate of https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/552? 😄

**Comment by mackoj** [comment] 2020-11-23 19:33
Sorry I didn't see the previous issue I will close this one.

**Closed** 2020-11-23 19:34 UTC

**Comment by daveverwer** [comment] 2020-11-23 19:37
Don't worry about it, Jeffrey! Thanks so much for the suggestion.
