### ISSUE TITLE
Only show a pre tagged version if the version number is greater than the stable version

### ISSUE THREAD

**Issue by daveverwer** [SwiftPackageIndex/SwiftPackageIndex-Server#489] opened 2020-06-28 13:07 UTC
For example:

https://swiftpackageindex.com/vapor/fluent

<img width="506" alt="Screenshot 2020-06-28 at 14 05 49@2x" src="https://user-images.githubusercontent.com/5180/85948375-7e8a5400-b948-11ea-912b-a4da8160652d.png">

https://swiftpackageindex.com/sunshinejr/SwiftyUserDefaults

<img width="529" alt="Screenshot 2020-06-28 at 14 06 16@2x" src="https://user-images.githubusercontent.com/5180/85948385-8cd87000-b948-11ea-9969-7a9bf67c996b.png">

I'm 99.9% sure we fixed this in the past, so this may be a regression.

**Comment by finestructure** [comment] 2020-09-14 07:50
Duplicate of #188 , most recently fixed here: #697

**Closed by finestructure** 2020-09-14 07:50 UTC
Labels: bug
